{% set name = "pyModbusTCP" %}
{% set version = "0.1.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/sourceperl/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 1f8be12eab1354a84fbf52df3d76fc2ffaa400e69173bcf460a6a5bce6b98b9f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  source_files:
    - tests/test_*.py

about:
  home: http://github.com/sourceperl/pyModbusTCP
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A simple Modbus/TCP client library for Python
  description: |
    A simple Modbus/TCP client library for Python
  doc_url: http://pymodbustcp.readthedocs.io/
  dev_url: https://github.com/sourceperl/pyModbusTCP

extra:
  recipe-maintainers:
    - awacha
