{% set name = "pyModbusTCP" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/sourceperl/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: f130bfd3e367e33c53071196d08ca2c2e6d41923de9cffc15ce566306323a062

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  source_files:
    - tests/test_*.py

about:
  home: http://github.com/sourceperl/pyModbusTCP
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A simple Modbus/TCP client library for Python'
  description: |
    A simple Modbus/TCP client library for Python
  doc_url: http://pymodbustcp.readthedocs.io/
  dev_url: https://github.com/sourceperl/pyModbusTCP

extra:
  recipe-maintainers:
    - awacha
