travis:
  secure:
    BINSTAR_TOKEN: rC0+i/Cxr9WAXUGAr1cRDtPRftY8XiTdtkGL0Yw/jX1xjN/js0GOsCfYhtQ+Y9RVdBFa58JXZMMzmN/0Hd4fIDAEdCHwnAWei/KInGLJ3FFkm3G842+yTlXDYDN3Cv9fQh2PE5ZxB3Kizo+GzFS/oie3Am69CWp3lqLmV88yHWrlSNjYLRjL7kaEciQdJcgm6ELpVNQcQHJYW+ofQfpwy+2AHtK63fISQzHeleQD9iD936eahIm0uFP72naRVkSOvxhYKfrPgBDfBxbweh120LF20ImIje0+l8HNXcB96JV7exT983C5ORaeN3OI1/Gzzy10B8t3zYSgR2UU+bB5Rtzq8Fqr6UYI76h3tz56TeSgjA1SLh2A/ohFfifrGP92zVBnuM4Rq3Nn5TPOOjf9q0DQ45aevvgB9S8IqoIrzj5Y0/aRvgGSpx8x1zIUyk3zMmbQZsy+6DkrClol7I1cHWQ2nOda6Kn6zfqH+UfUi3BJ9GVtfzGcEs6daJ+4K3CikCAFWptQ72dxzxg3jOqASjfeiLo2EJBWac9/NaOg1FMMKJ0F3i+LpQH1yS+heX+8/y5dzqHR2T+Jk0eNeTWhSJlz6qMMBob611J6xS1RZuaEJXQJIQavKshi4jME/fNR3U5r4fIsdKxwRsQHGjf+/JwuYlAlVzzdKRXZ9uZDcG4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
